name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Merge change
        run: |
          git checkout master_ready
          git merge master
      
      - name: Install python package
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
          
      - name: Create folder & Generate dag
        run: |
          cd ./wilson
          mkdir -p "dag_py_folder"
          python test.py
      
      - name: Commit change
        run: |
          git add -A
          git commit --allow-empty -m "Github Action Auto Commit"
      
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[CI-BOT] Auto merge"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: github_actions_beta_branch
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            This PR is auto-generated by github-action bot
