name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: List branchs
        run: git branch -r
      
      - name: Create folder
        run: |
          mkdir -p test
        
      - name: Push
        run: |
          git config --global user.email "wang83083030@gmail.com"
          git config --global user.name "Wilson Wang"
          git checkout origin/test
      
      - name: List files
        run: ls
      
