name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          cd ./$PIPELINE_FOLDER_PATH
          mkdir -p "dag_py_folder"
      - name: step2
        run: |
          pwd
          cd ./$PIPELINE_FOLDER_PATH
          ls
