name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set git config
        run: |
          git config --global user.email "wang83083030@gmail.com"
          git config --global user.name "Wilson Wang"
      
      - name: Merge change
        run: |
          git checkout master_ready
          git merge master
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: execute py script
        run: python test.py
      
      - name: Push change
        run: |
          git push origin master_ready     
          
#       - name: step1
#         run: |
#           cd ./wilson
#           mkdir -p "dag_py_folder"
          
#       - name: step2
#         run: |
#           pwd
#           cd ./wilson
#           ls
