name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: List branchs
        run: git branch -r
      
#       - name: Create folder
#         run: |
#           mkdir -p test
      - name: Deploy
        uses: codingforentrepreneurs/action-branch-to-branch@main
        with:
          dest_branch: 'master_ready'
          source_branch: 'master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
#       - name: List files after
#         run: ls
      
