name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Declare environment variable
        run: |
          echo "TEMP_BRANCH=$(uuidgen)" >> $GITHUB_ENV
      
      - name: Echo temp branch
        run: |
          echo $TEMP_BRANCH
      
      - name: Create branch
        run: |
          git checkout -b $TEMP_BRANCH
          git push -u origin $TEMP_BRANCH
      
      - name: Delete branch
        run: |
          git push --delete origin $TEMP_BRANCH
