name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup config
        run: |
          git config --local user.email "testwilson0830@github.com"
          git config --local user.name "GitHub Actions"
      
      - name: Merge change
        run: |
          git checkout master_ready
          git merge master
      
      - name: Install python package
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
          
      - name: Create folder & Generate dag
        run: |
          cd ./wilson
          mkdir -p "dag_py_folder"
          python test.py
      
      - name: Commit change
        run: |
          git add -A
          git commit --allow-empty -m "Github Actions Auto Commit"
      
      - name: Create Pull Request
        id: create_pull_request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "[CI-BOT] Auto merge"
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: github_actions_beta_branch
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          body: |
            This PR is auto-generated by github-actions bot

      - name: Auto approve
        if: steps.create_pull_request.outputs.pull-request-operation == 'created'
        uses: hmarr/auto-approve-action@v3
        with:
          github-token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          review-message: "Auto approved automated PR"
          
      - name: Enable Pull Request Automerge
        if: steps.create_pull_request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create_pull_request.outputs.pull-request-number }}
          merge-method: merge
