name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: List branchs
        run: git branch -r
      
      - name: Merge changes
        run: |
          git config --global user.email "wang83083030@gmail.com"
          git config --global user.name "Wilson Wang"
          git checkout master_ready
          git merge master
          mkdir -p "py_folder"
          find "." -name '*.yaml' -type f | while read file; do
              filename=$(basename "$file" .yaml)
              echo $filename
              cp "$file" "py_folder/$filename.txt"
          done
          git add -A
          git commit -m "Github Action Auto Commit"
          git push origin master_ready
      
