name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      
      - name: List branchs
        run: git branch -r
        
      - name: Push
        run: |
          git add .
          git commit -m  "github actions auto sync"
          git push origin/test
        
        
