name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: |
          pwd
          echo =============
          ls
          
#       - name: step2
#         run: |
#           pwd
#           cd ./wilson
#           ls
#           cd ./wilson
#           mkdir -p "dag_py_folder"
