name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: step1
        run: |
          cd ./wilson
          mkdir -p "dag_py_folder"
          
      - name: step2
        run: |
          pwd
          cd ./wilson
          ls
