name: CI
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup git config
        run: |
          git config --global user.email "wang83083030@gmail.com"
          git config --global user.name "Wilson Wang"
      
      - name: Merge change
        run: |
          git checkout master_ready
          git merge master
      
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install python package
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML
          
      - name: Create folder
        run: |
          cd ./wilson
          mkdir -p "dag_py_folder"
          
      - name: Execute py script
        run: |
          pwd
          python test.py
      
      - name: Push change
        run: |
          git add -A
          git commit -m "Github Action Auto Commit"
          git push origin master_ready
